%% Flume Experiments

format compact
format shorte
close all
clear
clc

%% Data

% Data is arranged as q [mbar] V_ref [m/s] Apla [deg] AF/AF2 [N] PM/YM
% [N-cm] P[mbar]

load('OverallData.mat')

%% Equations

load('Equations.mat')

%% Analysis Values

load('Analysis.mat')

%% Making Tables

Constant100LiftCoefficient(end+1)=NaN;
Constant100LiftCoefficient(end+1)=NaN;
Constant100LiftCoefficientUncertainty(end+1)=NaN;
Constant100LiftCoefficientUncertainty(end+1)=NaN;

CoefficientofLiftTable=...
    [NonConstant80LiftCoefficient NonConstant80LiftCoefficientUncertainty...
    Constant80LiftCoefficient Constant80LiftCoefficientUncertainty...
    NonConstant100LiftCoefficient NonConstant100LiftCoefficientUncertainty...
    Constant100LiftCoefficient Constant100LiftCoefficientUncertainty...
    FlapNonConstant80LiftCoefficient FlapNonConstant80LiftCoefficientUncertainty...
    SlatFlapNonConstant80LiftCoefficient SlatFlapNonConstant80LiftCoefficientUncertainty];

Constant100DragCoefficient(end+1)=NaN;
Constant100DragCoefficient(end+1)=NaN;
Constant100DragCoefficientUncertainty(end+1)=NaN;
Constant100DragCoefficientUncertainty(end+1)=NaN;

CoefficientofDragTable=...
    [NonConstant80DragCoefficient NonConstant80DragCoefficientUncertainty...
    Constant80DragCoefficient Constant80DragCoefficientUncertainty...
    NonConstant100DragCoefficient NonConstant100DragCoefficientUncertainty...
    Constant100DragCoefficient Constant100DragCoefficientUncertainty...
    FlapNonConstant80DragCoefficient FlapNonConstant80DragCoefficientUncertainty...
    SlatFlapNonConstant80DragCoefficient SlatFlapNonConstant80DragCoefficientUncertainty];

ReynoldsTable=...
    [NonConstant80Reynolds NonConstant80ReynoldsUncertainty...
    Constant80Reynolds Constant80ReynoldsUncertainty...
    NonConstant100Reynolds NonConstant100ReynoldsUncertainty...
    Constant100Reynolds Constant100ReynoldsUncertainty...
    FlapNonConstant80Reynolds FlapNonConstant80ReynoldsUncertainty...
    SlatFlapNonConstant80Reynolds SlatFlapNonConstant80ReynoldsUncertainty];











NonConstant80=[NonConstant80(:,3),...
    CorrectionNonConstant80(:,1),...
    ReynoldsTable(:,1:2),...
    CoefficientofLiftTable(:,1:2),...
    CoefficientofDragTable(:,1:2),...
    CorrectionNonConstant80(:,2)];

Constant80=[Constant80(:,3),...
    CorrectionConstant80(:,1),...
    ReynoldsTable(:,3:4),...
    CoefficientofLiftTable(:,3:4),...
    CoefficientofDragTable(:,3:4),...
    CorrectionConstant80(:,2)];

NonConstant100=[NonConstant100(:,3),...
    CorrectionNonConstant100(:,1),...
    ReynoldsTable(:,5:6),...
    CoefficientofLiftTable(:,5:6),...
    CoefficientofDragTable(:,5:6),...
    CorrectionNonConstant100(:,2)];

Constant100=[Constant100(:,3),...
    CorrectionConstant100(:,1),...
    ReynoldsTable(1:end-2,7:8),...
    CoefficientofLiftTable(1:end-2,7:8),...
    CoefficientofDragTable(1:end-2,7:8),...
    CorrectionConstant100(:,2)];

FlapNonConstant80=[FlapNonConstant80(:,3),...
    FlapCorrectionNonConstant80(:,1),...
    ReynoldsTable(:,9:10),...
    CoefficientofLiftTable(:,9:10),...
    CoefficientofDragTable(:,9:10),...
    FlapCorrectionNonConstant80(:,2)];

SlatFlapNonConstant80=[SlatFlapNonConstant80(:,3),...
    FlapCorrectionNonConstant80(:,1),...
    ReynoldsTable(:,11:12),...
    CoefficientofLiftTable(:,11:12),...
    CoefficientofDragTable(:,11:12),...
    SlatFlapCorrectionNonConstant80(:,2)];

%% Saving
save('Tables.mat')

%% Junk

Constant100(end+1,:)=NaN;
Constant100(end+1,:)=NaN;
ReynoldStandardDeviation=[NonConstant80(:,3) Constant80(:,3) NonConstant100(:,3) Constant100(:,3) FlapNonConstant80(:,3) SlatFlapNonConstant80(:,3)];
nanstd(ReynoldStandardDeviation)