%% Conduction Heat Transfer Lab

format compact
format long
close all
clear
clc

%% Data Section

run('Conduction_Heat_Transfer_Lab_Data.m')
    save(...
        'Data',...
        'Control_no_Paste',...
        'Control_2_Paste',...
        'TS1',...
        'TS2',...
        'x1',...
        'x2',...
        'x3',...
        'x1_error',...
        'x2_error',...
        'x3_error',...
        'p1',...
        'p2',...
        'p3',...
        'p4',...
        'p5',...
        'p6',...
        'p1_error',...
        'p2_error',...
        'p3_error',...
        'p4_error',...
        'p5_error',...
        'p6_error',...
        'Diameter',...
        'Diameter_error',...
        'Voltage',...
        'Voltage_error',...
        'Current',...
        'Current_error'...
        )

%% Plot Section

run('Conduction_Heat_Transfer_Lab_Plots.m')
    savefig(1,'Control_no_Paste.fig')
    saveas(1,'Control_no_Paste.png')
    savefig(2,'Control_2_Paste.fig')
    saveas(2,'Control_2_Paste.png')
    savefig(3,'TS1.fig')
    saveas(3,'TS1.png')
    savefig(4,'TS2.fig')
    saveas(4,'TS2.png')
    
%% Analysis Section

run('Conduction_Heat_Transfer_Lab_Analysis.m')
    savefig(1,'Control_no_Paste_Drops.fig')
    saveas(1,'Control_no_Paste_Drops.png')
    savefig(2,'Control_2_Paste_Drops.fig')
    saveas(2,'Control_2_Paste_Drops.png')
    savefig(3,'TS1_Drops.fig')
    saveas(3,'TS1_Drops.png')
    savefig(4,'TS2_Drops.fig')
    saveas(4,'TS2_Drops.png')
    save(...
        'Analysis',...
        'Slope_Control_no_Paste_Temperature',...
        'k_Control_no_Paste_line1',...
        'k_Control_no_Paste_line2',...
        'k_Control_no_Paste_line3',...
        'Control_no_Paste_Thermal_Resitance1',...
        'Control_no_Paste_Thermal_Resitance2',...
        'Control_no_Paste_Q_with_R',...
        'Control_no_Paste_Q_without_R',...
        'Slope_Control_2_Paste_Temperature',...
        'k_Control_2_Paste_line1',...
        'k_Control_2_Paste_line2',...
        'k_Control_2_Paste_line3',...
        'Control_2_Paste_Thermal_Resitance1',...
        'Control_2_Paste_Thermal_Resitance2',...
        'Control_2_Paste_Q_with_R',...
        'Control_2_Paste_Q_without_R',...
        'Slope_TS1_Temperature',...
        'k_TS1_line1',...
        'k_TS1_line2',...
        'k_TS1_line3',...
        'TS1_Thermal_Resitance1',...
        'TS1_Thermal_Resitance2',...
        'TS1_Q_with_R',...
        'TS1_Q_without_R',...
        'Slope_TS2_Temperature',...
        'k_TS2_line1',...
        'k_TS2_line2',...
        'k_TS2_line3',...
        'TS2_Thermal_Resitance1',...
        'TS2_Thermal_Resitance2',...
        'TS2_Q_with_R',...
        'TS2_Q_without_R',...
        'Average_k',...
        'k_Control_no_Paste_line1_10'...
        )